[database]
data_store = "mysql://root:Mani@2003@tcp(192.168.5.103:3306)/gorse_db"
cache_store = "redis://192.168.5.103:6379"

[server]
host = "0.0.0.0"
port = 8088
api_key = "zhenghaoz"

[master]
host = "0.0.0.0"
port = 8087

[dashboard]
host = "0.0.0.0"
port = 8089

[worker]
host = "0.0.0.0"

[recommend]
cache_size = 100
